# Generated by Django 2.2 on 2019-04-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190423_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
