# Generated by Django 2.2 on 2019-04-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_learn_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('main_topic', models.CharField(max_length=45)),
                ('sub_topic', models.CharField(max_length=45)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Learn')),
            ],
        ),
    ]
