# Generated by Django 2.2 on 2019-04-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20190428_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='contentUrl',
            field=models.URLField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='description',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Learn'),
        ),
    ]
