# Generated by Django 2.2 on 2019-04-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20190428_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnname',
            name='main_topic',
            field=models.CharField(blank='True', max_length=45, null='True'),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Learn'),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='sub_topic',
            field=models.CharField(blank='True', max_length=45, null='True'),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='subject',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
    ]
