# Generated by Django 2.2 on 2019-04-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20190428_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnname',
            name='system',
            field=models.CharField(blank='True', max_length=45, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='learn',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Learn'),
        ),
        migrations.AlterField(
            model_name='learnname',
            name='subject',
            field=models.CharField(blank='True', max_length=35, null='True'),
        ),
    ]
