# Generated by Django 2.2 on 2019-05-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_auto_20190502_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='learnname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Learn'),
        ),
    ]
