# Generated by Django 2.2 on 2019-05-04 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_auto_20190504_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='main_topic',
            field=models.CharField(blank='True', max_length=45, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='learn',
            name='sub_topic',
            field=models.CharField(blank='True', max_length=45, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='learn',
            name='subject',
            field=models.CharField(blank='True', default='Pathology', max_length=25, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='learn',
            name='system',
            field=models.CharField(blank='True', default='Renal', max_length=45, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='learn',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LearnName',
        ),
    ]
