# Generated by Django 2.2 on 2019-05-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_auto_20190504_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learn',
            options={'ordering': ['-timestamp']},
        ),
    ]
